### ISSUE TITLE
enable a YAML molecular format derived from Z-Matrix reader

### ISSUE THREAD

**Issue by demianriccardi** [demianriccardi/HackaMol#16]
The YAML molecular format should allow for variables to be fed in as arrays.

currently debating simple vs flexible representations:

simple:
```yaml
---
atoms:
- N 0    0.483824   1.697569  -0.701935
- C 0    0.027824   0.314569  -0.780935
- C 0    0.152824  -0.407431   0.563065
- O 0   -0.559176  -1.416431   0.778065
- C 2   CC 3 CCC 4 CCCC
vars:
- CC :       1.54
- CCC :    106.42
- CCCC :  [-81.90, 89, 09]
```
flexible:
```yaml
---
atoms :
- N :  { '0' : [[0,0,0], [0.483824,   1.697569,  -0.701935]] }
- C :  { '0' : [[0.027824,   0.314569,  -0.780935]] }
- C :  { '0' : [[0.152824,  -0.407431,   0.563065]] }
- O :  { '0' :  [[-0.559176,  -1.416431,   0.778065]] }
- C :  { '2' : CC, '3' :CCC, '4' : CCCC }
vars:
- CC : [1.54]
- CCC :  [106.42]
- CCCC  : [-81.90, 80, 90]
```
